apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pmspec.fullname" . }}-secrets
  labels:
    {{- include "pmspec.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwtSecret | default (randAlphaNum 32) | b64enc | quote }}
